//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistrationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAssignments
    {
        public int AssignmentID { get; set; }
        public int OrderID { get; set; }
        public int EmployeeID { get; set; }
        public string RoleInOrder { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
