//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserRegistrationApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestID { get; set; }
        public int SubscriberID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestType { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Subscribers Subscribers { get; set; }
    }
}
